"""empty message

Revision ID: 12c81c1d2f8a
Revises: 66b2106c9c13
Create Date: 2025-11-11 02:38:36.731813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c81c1d2f8a'
down_revision = '66b2106c9c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needsLeash', sa.Boolean(), nullable=True))
        batch_op.alter_column('availability',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.String(length=45),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
        batch_op.drop_column('needsLeash')

    # ### end Alembic commands ###
