"""empty message

Revision ID: 267c71d902f8
Revises: 8d24ae9dad40
Create Date: 2025-10-25 08:01:10.463974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267c71d902f8'
down_revision = '8d24ae9dad40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('idPublicAccounts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('idPublicAccounts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
