"""empty message

Revision ID: 593c0a491e4a
Revises: b5c9b0688d0b
Create Date: 2025-10-19 12:22:34.958013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593c0a491e4a'
down_revision = 'b5c9b0688d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminAccounts',
    sa.Column('idAdminAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAdminAccounts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminAccounts')
    # ### end Alembic commands ###
