"""empty message

Revision ID: 5b278c117d48
Revises: 593c0a491e4a
Create Date: 2025-10-19 22:14:08.294667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b278c117d48'
down_revision = '593c0a491e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('idAnimals', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('breed', sa.String(length=45), nullable=True),
    sa.Column('disposition', sa.String(length=45), nullable=True),
    sa.Column('availability', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('numImages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idAnimals')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
