"""empty message

Revision ID: 8d24ae9dad40
Revises: 
Create Date: 2025-10-25 07:58:35.713417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d24ae9dad40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminAccounts',
    sa.Column('idAdminAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAdminAccounts')
    )
    op.create_table('publicAccounts',
    sa.Column('idPublicAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idPublicAccounts')
    )
    op.create_table('animals',
    sa.Column('idAnimals', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('breed', sa.String(length=45), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('numImages', sa.Integer(), nullable=False),
    sa.Column('idPublicAccounts', sa.Integer(), nullable=False),
    sa.Column('children', sa.Boolean(), nullable=False),
    sa.Column('dogs', sa.Boolean(), nullable=False),
    sa.Column('cats', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idPublicAccounts'], ['publicAccounts.idPublicAccounts'], ),
    sa.PrimaryKeyConstraint('idAnimals')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_birthday'), ['birthday'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_idPublicAccounts'), ['idPublicAccounts'], unique=False)

    op.create_table('animals_has_publicAccounts',
    sa.Column('idPublicAccounts', sa.Integer(), nullable=True),
    sa.Column('idAnimals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAnimals'], ['animals.idAnimals'], ),
    sa.ForeignKeyConstraint(['idPublicAccounts'], ['publicAccounts.idPublicAccounts'], )
    )
    op.create_table('newsPosts',
    sa.Column('idNewsPosts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('datePublished', sa.Date(), nullable=False),
    sa.Column('idAnimals', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idAnimals'], ['animals.idAnimals'], ),
    sa.PrimaryKeyConstraint('idNewsPosts')
    )
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsPosts_datePublished'), ['datePublished'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsPosts_idAnimals'), ['idAnimals'], unique=False)

    op.create_table('animals_has_newsPost',
    sa.Column('idAnimals', sa.Integer(), nullable=True),
    sa.Column('idNewsPosts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAnimals'], ['animals.idAnimals'], ),
    sa.ForeignKeyConstraint(['idNewsPosts'], ['newsPosts.idNewsPosts'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals_has_newsPost')
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsPosts_idAnimals'))
        batch_op.drop_index(batch_op.f('ix_newsPosts_datePublished'))

    op.drop_table('newsPosts')
    op.drop_table('animals_has_publicAccounts')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_idPublicAccounts'))
        batch_op.drop_index(batch_op.f('ix_animals_birthday'))

    op.drop_table('animals')
    op.drop_table('publicAccounts')
    op.drop_table('adminAccounts')
    # ### end Alembic commands ###
