"""empty message

Revision ID: 982007135c2b
Revises: 267c71d902f8
Create Date: 2025-10-25 09:04:27.707475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982007135c2b'
down_revision = '267c71d902f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals_has_newsPost')
    op.drop_table('animals_has_publicAccounts')
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.alter_column('idAnimals',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.alter_column('idAnimals',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('animals_has_publicAccounts',
    sa.Column('idPublicAccounts', sa.INTEGER(), nullable=True),
    sa.Column('idAnimals', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['idAnimals'], ['animals.idAnimals'], ),
    sa.ForeignKeyConstraint(['idPublicAccounts'], ['publicAccounts.idPublicAccounts'], )
    )
    op.create_table('animals_has_newsPost',
    sa.Column('idAnimals', sa.INTEGER(), nullable=True),
    sa.Column('idNewsPosts', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['idAnimals'], ['animals.idAnimals'], ),
    sa.ForeignKeyConstraint(['idNewsPosts'], ['newsPosts.idNewsPosts'], )
    )
    # ### end Alembic commands ###
