"""empty message

Revision ID: 9de5896d71a4
Revises: 
Create Date: 2025-11-23 05:04:43.342061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de5896d71a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('numImages', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('breed', sa.String(length=45), nullable=True),
    sa.Column('availability', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('numImages', sa.Integer(), nullable=False),
    sa.Column('children', sa.Boolean(), nullable=False),
    sa.Column('dogs', sa.Boolean(), nullable=False),
    sa.Column('cats', sa.Boolean(), nullable=False),
    sa.Column('needsLeash', sa.Boolean(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iduser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_birthday'), ['birthday'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_iduser'), ['iduser'], unique=False)

    op.create_table('newsPosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('datePublished', sa.Date(), nullable=False),
    sa.Column('idAnimal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAnimal'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsPosts_datePublished'), ['datePublished'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsPosts_idAnimal'), ['idAnimal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsPosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsPosts_idAnimal'))
        batch_op.drop_index(batch_op.f('ix_newsPosts_datePublished'))

    op.drop_table('newsPosts')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_iduser'))
        batch_op.drop_index(batch_op.f('ix_animals_birthday'))

    op.drop_table('animals')
    op.drop_table('users')
    # ### end Alembic commands ###
