"""empty message

Revision ID: b0f15b2178f6
Revises: 
Create Date: 2025-10-20 00:56:30.830419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f15b2178f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminAccounts',
    sa.Column('idAdminAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idAdminAccounts')
    )
    op.create_table('animals',
    sa.Column('idAnimals', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=45), nullable=False),
    sa.Column('breed', sa.String(length=45), nullable=True),
    sa.Column('disposition', sa.String(length=45), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('numImages', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idAnimals')
    )
    op.create_table('newsPost',
    sa.Column('idNewsPosts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=10000), nullable=False),
    sa.Column('datePublished', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idNewsPosts')
    )
    op.create_table('publicAccounts',
    sa.Column('idPublicAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idPublicAccounts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicAccounts')
    op.drop_table('newsPost')
    op.drop_table('animals')
    op.drop_table('adminAccounts')
    # ### end Alembic commands ###
