"""empty message

Revision ID: b5c9b0688d0b
Revises: 
Create Date: 2025-10-17 19:58:50.174908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c9b0688d0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicAccounts',
    sa.Column('idPublicAccounts', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('lastName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phoneNumber', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idPublicAccounts')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicAccounts')
    # ### end Alembic commands ###
